data_root: /home/eva_share/datasets/ILSVRC2012/ILSVRC2012_img_train
float_epoch: 0
print_freq: 50
NETWORK: 
    depth: 18
    num_classes: 1000
    batchnorm: true
    quantize: true
    q_cfg:
        bw:
            - 5
            - 6
            - 6
        linear: 
            - null
            - null
            - null
        signed: true
        stochastic: true
        erange: 
            - max
            - max
            - max
        group: 
            - nc
            - nc
            - nc
        level:
            - 1
            - 1
            - 1
        hard: pow
TRAIN: 
    epoch: 75 
    optimizer: SGDm
    resume: null
    evaluate: false
    learning_rate: 
        - 0.1
        - 0.01
        - 0.001
        - 0.0005
    decay_step:
        - 0
        - 23
        - 45
        - 65
    warmup: false
    weight_decay: 0.0001
    momentum: 0.7
DATA:
    dataset: ILSVRC2012_img
    batch_size: 1024
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.485
        - 0.456
        - 0.406
    pixel_stds:
        - 0.229
        - 0.224
        - 0.225
    valid_batch_size: 256
    valid_num_works: 8
LOG:
    frequent: 200
    types:
        - a
        - w
        - g
        - e
