data_root: /home/eva_share/datasets/ILSVRC2012/ILSVRC2012_img_train
float_epoch: 0
print_freq: 50
NETWORK: 
    depth: 18
    num_classes: 1000
    batchnorm: true
    quantize: true
    q_cfg:
        bw:
            - 10
            - 11
            - 11
        linear: 
            - null
            - null
            - null
        signed: true
        stochastic: true
        erange: 
            - max
            - max
            - max
        group: 
            - nc
            - nc
            - nc
        level:
            - 1
            - 1
            - 1
        hard: pow
TRAIN: 
    epoch: 73 
    optimizer: SGDm
    #resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200129_16-58-30/checkpoint_best_3.pkl
    resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200201_12-53-15/checkpoint_best_3.pkl
    evaluate: false
    learning_rate: 
        - 0.005
        - 0.001
    decay_step:
        - 0
        - 68
    warmup: false
    weight_decay: 0.0001
    momentum: 0.7
DATA:
    dataset: ILSVRC2012_img
    batch_size: 1024
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.485
        - 0.456
        - 0.406
    pixel_stds:
        - 0.229
        - 0.224
        - 0.225
    valid_batch_size: 256
    valid_num_works: 8
LOG:
    frequent: 200
