data_root: /home/eva_share/datasets/ILSVRC2012/ILSVRC2012_img_train
float_epoch: 1
print_freq: 50
NETWORK: 
    depth: 18
    num_classes: 1000
    batchnorm: true
    quantize: true
    q_cfg:
        bw:
            - 12
            - 13
            - 13
        linear: 
            - null
            - null
            - null
        signed: true
        stochastic: true
        erange: 
            - max
            - max
            - max
        group: 
            - nc
            - n
            - nc
        level:
            - 1
            - 1
            - 1
        hard: pow
TRAIN: 
    epoch: 80 
    optimizer: SGDm
    # old model
    #resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200104/checkpoint_60.pkl
    # from 60 484
    #resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200122_09-16-51/checkpoint_best_4.pkl
    # from 60 448
    #resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200121_07-54-43/checkpoint_best_4.pkl
    # new model
    #resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200127_23-48-40/checkpoint_60.pkl
    # resume2 new model
    #resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200130_15-35-14/checkpoint_best_3.pkl
    # resume3 new model
    #resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200131_01-23-37/checkpoint_best_3.pkl
    # resume 455 model
    #resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200203_00-56-59/checkpoint_best_3.pkl
    # resume 677 model
    resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200204_17-28-00/checkpoint_best_3.pkl
    evaluate: false
    learning_rate: 
        - 0.001
        - 0.0005
    decay_step:
        - 0
        - 75
    warmup: false
    weight_decay: 0.0001
    momentum: 0.8
DATA:
    dataset: ILSVRC2012_img
    batch_size: 1024
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.485
        - 0.456
        - 0.406
    pixel_stds:
        - 0.229
        - 0.224
        - 0.225
    valid_batch_size: 256
    valid_num_works: 8
LOG:
    frequent: 200
