data_root: /home/eva_share/datasets/ILSVRC2012/ILSVRC2012_img_train
float_epoch: 1
print_freq: 50
NETWORK: 
    depth: 18
    num_classes: 1000
    batchnorm: true
    quantize: false
    q_cfg:
        bw:
            - 4
            - 4
            - 4
        stochastic: true
        signed: false
        group: 
            - nc
            - n
            - nc
        level:
            - 3
            - 3
            - 3
        g_scale_type: complex
        value_type: progress
TRAIN: 
    epoch: 88 
    optimizer: SGDm
    resume: null
    evaluate: false
    learning_rate: 
        - 0.1
        - 0.01
        - 0.001
        - 0.0005
    decay_step:
        - 0
        - 29
        - 55
        - 80
    warmup: false
    weight_decay: 0.0005
    momentum: 0.9
DATA:
    dataset: ILSVRC2012_img
    batch_size: 1024
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.485
        - 0.456
        - 0.406
    pixel_stds:
        - 0.229
        - 0.224
        - 0.225
    valid_batch_size: 256
    valid_num_works: 8
LOG:
    frequent: 280
    types:
        - w
