data_root: /home/eva_share/datasets/ILSVRC2012/ILSVRC2012_img_train
float_epoch: 5
print_freq: 50
NETWORK: 
    depth: 18
    num_classes: 1000
    batchnorm: true
    quantize: true
    q_cfg:
        bw:
            - 4
            - 5
            - 6
        linear: 
            - 0
            - 0
            - 0
        signed: true
        stochastic: true
        dequantize: true
        group: false
        level:
            - 1
            - 1
            - 3
TRAIN: 
    epoch: 95
    optimizer: SGDm
    learning_rate: 
        - 0.12
        - 0.012
        - 0.0012
        - 0.0008
    decay_step:
        - 0
        - 30
        - 60
        - 88
    warmup: false
    weight_decay: 0.0001
    momentum: 0.9
DATA:
    dataset: ILSVRC2012_img
    batch_size: 512
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.4914
        - 0.4822
        - 0.4465
    pixel_stds:
        - 0.2023
        - 0.1994
        - 0.2010
    valid_batch_size: 256
    valid_num_works: 8
LOG:
    frequent: 1
    weight_log: false
    activation_log: false
    gradient_log: false
