data_root: /home/eva_share/datasets/ILSVRC2012/ILSVRC2012_img_train
float_epoch: 1
print_freq: 50
NETWORK: 
    arch: resnet
    depth: 34
    num_classes: 1000
    batchnorm: true
    quantize: true
    q_cfg: 
        bw:
            - 4
            - 4
            - 4
        level:
            - 2
            - 2
            - 2
        stochastic: true
        signed: false
        qfirst: false
        group: 
            - nc
            - c
            - nc
        g_scale_type: complex
        value_type: progress
TRAIN: 
    epoch: 85 
    optimizer: SGDm
    resume: null
    evaluate: false
    learning_rate: 
        - 0.1
        - 0.01
        - 0.001
        - 0.0005
    decay_step:
        - 0
        - 30
        - 60
        - 80
    warmup: false
    weight_decay: 0.0001
    momentum: 0.9
DATA:
    dataset: ILSVRC2012_img
    batch_size: 256
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    valid_batch_size: 256
    valid_num_works: 8
LOG:
    frequent: 300
    types:
        - w
