data_root: /home/eva_share/datasets/ILSVRC2012/ILSVRC2012_img_train
float_epoch: 0
print_freq: 50
NETWORK: 
    depth: 18
    num_classes: 1000
    batchnorm: true
    quantize: false
    q_cfg:
        bw:
            - 8
            - 8
            - 4
        linear: 
            - null
            - null
            - null
        signed: true
        stochastic: true
        erange: 
            - max
            - max
            - max
        group: 
            - n
            - c
            - n
        level:
            - 1
            - 1
            - 1
TRAIN: 
    epoch: 90 
    optimizer: SGDm
    #resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200104/checkpoint_60.pkl
    # from 60 484
    resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200122_09-16-51/checkpoint_best_4.pkl
    # from 60 448
    #resume: ../checkpoint/fix_experiment/imgnet/log_quantize_20200121_07-54-43/checkpoint_best_4.pkl
    evaluate: true
    learning_rate: 
        - 0.0012
        - 0.0012
        - 0.0012
        - 0.0006
    decay_step:
        - 0
        - 27
        - 55
        - 78
    warmup: false
    weight_decay: 0.0001
    momentum: 0.9
DATA:
    dataset: ILSVRC2012_img
    batch_size: 512
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.485
        - 0.456
        - 0.406
    pixel_stds:
        - 0.229
        - 0.224
        - 0.225
    valid_batch_size: 256
    valid_num_works: 8
LOG:
    frequent: 200
