data_root: /home/eva_share/datasets/ILSVRC2012/ILSVRC2012_img_train
float_epoch: 1
print_freq: 50
NETWORK: 
    depth: 18
    num_classes: 1000
    batchnorm: true
    quantize: true
    q_cfg:
        bw:
            - 6
            - 6
            - 6
        stochastic: false
        qfirst: false
        group: 
            - nc
            - n
            - nc
        level:
            - 1
            - 1
            - 1
        hard: pows
TRAIN: 
    epoch: 5 
    optimizer: SGDm
    resume: null
    evaluate: false
    learning_rate: 
        - 0.1
        - 0.01
        - 0.001
    decay_step:
        - 0
        - 2
        - 4
    warmup: false
    weight_decay: 0.0005
    momentum: 0.9
DATA:
    dataset: ILSVRC2012_img
    batch_size: 1024
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.485
        - 0.456
        - 0.406
    pixel_stds:
        - 0.229
        - 0.224
        - 0.225
    valid_batch_size: 256
    valid_num_works: 8
LOG:
    frequent: 3
    types:
        - a
        - w
        - g
        - e
