data_root: /home/zhongkai/experiment/pruning/VGGCIFAR/datasets/
parallel: false
visible_device: '1'
NETWORK: 
    depth: 20
    class_num: 10
    batchnorm: true
    pruning: false
    quantize: false
    quantize_cfg:
        bw:
            - 8
            - 8
            - 8
            - 16
        basis: this
    asparse: false
    asparse_cfg: null
    wsparse: false
    wsparse_cfg: null
TRAIN: 
    epoch: 170
    optimizer: SGDm
    learning_rate: 
        - 0.1
        - 0.01
        - 0.001
    decay_step:
        - 0
        - 81
        - 122
    warmup: false
    weight_decay: 0.0001
    momentum: 0.9
DATA:
    dataset: cifar10
    batch_size: 128
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.4914
        - 0.4822
        - 0.4465
    pixel_vars:
        - 0.2023
        - 0.1994
        - 0.2010
    valid_batch_size: 128
    valid_num_works: 8
LOG:
    frequent: 1
    weight_log: false
    activation_log: false
    gradient_log: false
    sparse_rate_log: false
