!!python/object/new:easydict.EasyDict
dictitems:
  DATA: &id013 !!python/object/new:easydict.EasyDict
    dictitems:
      batch_size: 128
      dataset: cifar10
      flip: true
      num_works: 8
      pixel_means: &id003 !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - 0
          - 1
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          F0hQ/Bhz3z+VZYhjXdzeP/p+arx0k9w/
      pixel_stds: &id004 !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - *id002
        - false
        - !!binary |
          24r9ZffkyT9nRGlv8IXJP+58PzVeusk/
      random_crop_pad: 4
      shuffle: true
      valid_batch_size: 128
      valid_num_works: 8
    state:
      batch_size: 128
      dataset: cifar10
      flip: true
      num_works: 8
      pixel_means: *id003
      pixel_stds: *id004
      random_crop_pad: 4
      shuffle: true
      valid_batch_size: 128
      valid_num_works: 8
  LOG: &id014 !!python/object/new:easydict.EasyDict
    dictitems:
      frequent: 200
      types: null
    state:
      frequent: 200
      types: null
  NETWORK: &id015 !!python/object/new:easydict.EasyDict
    dictitems:
      arch: resnet
      batchnorm: true
      depth: 20
      num_classes: 10
      pretrained: false
      q_cfg: &id010 !!python/object/new:easydict.EasyDict
        dictitems:
          bw: &id005
          - 8
          - 8
          - 8
          erange: &id006
          - max
          - max
          - max
          group: &id007
          - false
          - false
          - false
          hard: pow
          level: &id008
          - 0
          - 0
          - 0
          linear: &id009
          - null
          - null
          - null
          qbn: false
          qfirst: false
          qlinear: false
          signed: true
          stochastic: false
        state:
          bw: *id005
          erange: *id006
          group: *id007
          hard: pow
          level: *id008
          linear: *id009
          qbn: false
          qfirst: false
          qlinear: false
          signed: true
          stochastic: false
      quantize: false
    state:
      arch: resnet
      batchnorm: true
      depth: 20
      num_classes: 10
      pretrained: false
      q_cfg: *id010
      quantize: false
  TRAIN: &id016 !!python/object/new:easydict.EasyDict
    dictitems:
      decay_step: &id011
      - 0
      - 81
      - 122
      epoch: 165
      evaluate: false
      learning_rate: &id012
      - 0.1
      - 0.001
      - 0.0001
      momentum: 0.9
      optimizer: SGDm
      resume: null
      warmup: false
      weight_decay: 0.0005
    state:
      decay_step: *id011
      epoch: 165
      evaluate: false
      learning_rate: *id012
      momentum: 0.9
      optimizer: SGDm
      resume: null
      warmup: false
      weight_decay: 0.0005
  checkpoint_freq: 30
  cuda: true
  data_root: ''
  dist_backend: nccl
  dist_url: tcp://127.0.0.1:9000
  distributed: false
  float_epoch: 0
  multiprocessing_distributed: true
  parallel: true
  print_freq: 30
  random_seed: null
  rank: -1
  visible_device: '0'
  world_size: -1
state:
  DATA: *id013
  LOG: *id014
  NETWORK: *id015
  TRAIN: *id016
  checkpoint_freq: 30
  cuda: true
  data_root: ''
  dist_backend: nccl
  dist_url: tcp://127.0.0.1:9000
  distributed: false
  float_epoch: 0
  multiprocessing_distributed: true
  parallel: true
  print_freq: 30
  random_seed: null
  rank: -1
  visible_device: '0'
  world_size: -1
