data_root: /home/eva_share/datasets/
float_epoch: 2
print_freq: 50
NETWORK: 
    arch: resnet
    depth: 20
    num_classes: 10
    batchnorm: true
    quantize: true
    q_cfg:
        bw:
            - 8
            - 8
            - 8
        linear: 
            - null
            - tan
            - null
        signed: true
        stochastic: true
        erange:
            - max
            - max
            - max
        group: 
            - nc
            - n
            - nc
        level:
            - 0
            - 0
            - 0
        hard: pow
TRAIN: 
    epoch: 17
    optimizer: SGDm
    learning_rate: 
        - 0.1
        - 0.01
        - 0.001
    decay_step:
        - 0
        - 8
        - 12
    warmup: false
    weight_decay: 0.0001
    momentum: 0.9
DATA:
    dataset: cifar10
    batch_size: 128
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.4914
        - 0.4822
        - 0.4465
    pixel_stds:
        - 0.2023
        - 0.1994
        - 0.2010
    valid_batch_size: 256
    valid_num_works: 8
LOG:
    frequent: 3
    types:
        - e
        - a
        - w
        - g
