data_root: /home/eva_share/datasets/
float_epoch: 200
print_freq: 50
NETWORK: 
    depth: 20
    num_classes: 10
    batchnorm: true
    quantize: true
    q_cfg:
        bw:
            - 4
            - 4
            - 4
        linear: 
            - null
            - null
            - null
        signed: true
        stochastic: true
        erange:
            - max
            - max
            - max
        group: 
            - nt
            - nc
            - nt
        level:
            - 0
            - 0
            - 1
TRAIN: 
    epoch: 180
    optimizer: SGDm
    learning_rate: 
        - 0.125
        - 0.0156
        - 0.0015
        - 0.0008
    decay_step:
        - 0
        - 81
        - 122
        - 164
    warmup: false
    weight_decay: 0.0001
    momentum: 0.9
DATA:
    dataset: cifar10
    batch_size: 128
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.4914
        - 0.4822
        - 0.4465
    pixel_stds:
        - 0.2023
        - 0.1994
        - 0.2010
    valid_batch_size: 256
    valid_num_works: 8
LOG:
    frequent: 30
    types:
        - e
        - a
        - w
