data_root: /home/eva_share/datasets/
float_epoch: 1
print_freq: 50
NETWORK: 
    num_classes: 10
    batchnorm: true
    quantize: true
    q_cfg:
        bw:
            - 3
            - 3
            - 3
TRAIN: 
    epoch: 6
    optimizer: SGDm
    learning_rate: 
        - 0.1
        - 0.01
        - 0.001
        - 0.0005
    decay_step:
        - 0
        - 81
        - 122
        - 163
    warmup: false
    weight_decay: 0.0005
    momentum: 0.9
DATA:
    dataset: cifar10
    batch_size: 128
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    pixel_means: 
        - 0.4914
        - 0.4822
        - 0.4465
    pixel_stds:
        - 0.2023
        - 0.1994
        - 0.2010
    valid_batch_size: 128
    valid_num_works: 8
LOG:
    frequent: 2
    types:
        - w
        - g
        - a
        - e
