data_root: /home/eva_share/datasets/
float_epoch: 1
print_freq: 50
NETWORK: 
    arch: googlenet
    num_classes: 10
    batchnorm: true
    quantize: true
    q_cfg:
        bw:
            - 2
            - 2
            - 2
        level:
            - 2
            - 2
            - 2
        stochastic: true
        signed: false
        qfirst: false
        group:
            - n
            - c
            - n
        g_scale_type: complex
        value_type: progress
TRAIN: 
    epoch: 170
    optimizer: SGDm
    learning_rate: 
        - 0.1
        - 0.01
        - 0.001
        - 0.0005
    decay_step:
        - 0
        - 80
        - 120
        - 160
    warmup: false
    weight_decay: 0.0005
    momentum: 0.9
DATA:
    dataset: cifar10
    batch_size: 128
    num_works: 8
    flip: true
    shuffle: true
    random_crop_pad: 4
    valid_batch_size: 128
    valid_num_works: 8
LOG:
    frequent: 200
    types:
        - g
